// mosey's application-layer authentication handshake. Carried on
// the libp2p stream `/mosey/auth/1.0.0` as length-delimited
// [AuthMessage] envelopes. The underlying transport already
// provides confidentiality + integrity (libp2p Noise, TLS, etc.);
// this exchange just proves both parties hold the workspace's
// shared secret.
//
// Three-message flow:
//
//   1. Client → Server: ClientHello { nonce_c }
//   2. Server → Client: ServerProof { nonce_s, mac_s }
//   3. Client → Server: ClientProof { mac_c }
//
//   mac_s = HMAC(secret, "mosey-auth-v1:S" || nonce_c || nonce_s)
//   mac_c = HMAC(secret, "mosey-auth-v1:C" || nonce_s || nonce_c)
//
// Direction-specific MAC strings stop a passive attacker that
// observes one direction's MAC from replaying it in the other.
// Random nonces stop replay of an entire transcript.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: internal/api/auth.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*AuthMessage_ClientHello
	//	*AuthMessage_ServerProof
	//	*AuthMessage_ClientProof
	Kind          isAuthMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthMessage) Reset() {
	*x = AuthMessage{}
	mi := &file_internal_api_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMessage) ProtoMessage() {}

func (x *AuthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthMessage.ProtoReflect.Descriptor instead.
func (*AuthMessage) Descriptor() ([]byte, []int) {
	return file_internal_api_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthMessage) GetKind() isAuthMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *AuthMessage) GetClientHello() *ClientHello {
	if x != nil {
		if x, ok := x.Kind.(*AuthMessage_ClientHello); ok {
			return x.ClientHello
		}
	}
	return nil
}

func (x *AuthMessage) GetServerProof() *ServerProof {
	if x != nil {
		if x, ok := x.Kind.(*AuthMessage_ServerProof); ok {
			return x.ServerProof
		}
	}
	return nil
}

func (x *AuthMessage) GetClientProof() *ClientProof {
	if x != nil {
		if x, ok := x.Kind.(*AuthMessage_ClientProof); ok {
			return x.ClientProof
		}
	}
	return nil
}

type isAuthMessage_Kind interface {
	isAuthMessage_Kind()
}

type AuthMessage_ClientHello struct {
	ClientHello *ClientHello `protobuf:"bytes,1,opt,name=client_hello,json=clientHello,proto3,oneof"`
}

type AuthMessage_ServerProof struct {
	ServerProof *ServerProof `protobuf:"bytes,2,opt,name=server_proof,json=serverProof,proto3,oneof"`
}

type AuthMessage_ClientProof struct {
	ClientProof *ClientProof `protobuf:"bytes,3,opt,name=client_proof,json=clientProof,proto3,oneof"`
}

func (*AuthMessage_ClientHello) isAuthMessage_Kind() {}

func (*AuthMessage_ServerProof) isAuthMessage_Kind() {}

func (*AuthMessage_ClientProof) isAuthMessage_Kind() {}

// ClientHello is the first message: the dialer picks 32 random
// bytes and sends them as a challenge. `label` is an unauthenticated
// hint telling the server which configured secret/role to verify
// against — useful when the server has multiple secrets (owner +
// reader). Empty label means "owner" (the historical single-secret
// default).
//
// The label is just a hint: the server uses it to look up the
// right key, then runs the standard MAC verification. A client that
// lies about the label can't produce a valid MAC against a
// different key, so the handshake fails as it should.
type ClientHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_internal_api_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_internal_api_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ClientHello) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *ClientHello) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// ServerProof is the listener's response: its own 32-byte nonce
// plus the HMAC over both nonces proving it knows the secret.
type ServerProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Mac           []byte                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerProof) Reset() {
	*x = ServerProof{}
	mi := &file_internal_api_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerProof) ProtoMessage() {}

func (x *ServerProof) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerProof.ProtoReflect.Descriptor instead.
func (*ServerProof) Descriptor() ([]byte, []int) {
	return file_internal_api_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ServerProof) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *ServerProof) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

// ClientProof is the dialer's confirmation: the symmetric HMAC
// proving it knows the secret, computed over the reversed nonce
// order.
type ClientProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           []byte                 `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientProof) Reset() {
	*x = ClientProof{}
	mi := &file_internal_api_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientProof) ProtoMessage() {}

func (x *ClientProof) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientProof.ProtoReflect.Descriptor instead.
func (*ClientProof) Descriptor() ([]byte, []int) {
	return file_internal_api_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ClientProof) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

var File_internal_api_auth_proto protoreflect.FileDescriptor

const file_internal_api_auth_proto_rawDesc = "" +
	"\n" +
	"\x17internal/api/auth.proto\x12\bmosey.v1\"\xc9\x01\n" +
	"\vAuthMessage\x12:\n" +
	"\fclient_hello\x18\x01 \x01(\v2\x15.mosey.v1.ClientHelloH\x00R\vclientHello\x12:\n" +
	"\fserver_proof\x18\x02 \x01(\v2\x15.mosey.v1.ServerProofH\x00R\vserverProof\x12:\n" +
	"\fclient_proof\x18\x03 \x01(\v2\x15.mosey.v1.ClientProofH\x00R\vclientProofB\x06\n" +
	"\x04kind\"9\n" +
	"\vClientHello\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"5\n" +
	"\vServerProof\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\fR\x03mac\"\x1f\n" +
	"\vClientProof\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\fR\x03macB7Z5github.com/firefly-engineering/mosey/internal/api;apib\x06proto3"

var (
	file_internal_api_auth_proto_rawDescOnce sync.Once
	file_internal_api_auth_proto_rawDescData []byte
)

func file_internal_api_auth_proto_rawDescGZIP() []byte {
	file_internal_api_auth_proto_rawDescOnce.Do(func() {
		file_internal_api_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_auth_proto_rawDesc), len(file_internal_api_auth_proto_rawDesc)))
	})
	return file_internal_api_auth_proto_rawDescData
}

var file_internal_api_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_api_auth_proto_goTypes = []any{
	(*AuthMessage)(nil), // 0: mosey.v1.AuthMessage
	(*ClientHello)(nil), // 1: mosey.v1.ClientHello
	(*ServerProof)(nil), // 2: mosey.v1.ServerProof
	(*ClientProof)(nil), // 3: mosey.v1.ClientProof
}
var file_internal_api_auth_proto_depIdxs = []int32{
	1, // 0: mosey.v1.AuthMessage.client_hello:type_name -> mosey.v1.ClientHello
	2, // 1: mosey.v1.AuthMessage.server_proof:type_name -> mosey.v1.ServerProof
	3, // 2: mosey.v1.AuthMessage.client_proof:type_name -> mosey.v1.ClientProof
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_api_auth_proto_init() }
func file_internal_api_auth_proto_init() {
	if File_internal_api_auth_proto != nil {
		return
	}
	file_internal_api_auth_proto_msgTypes[0].OneofWrappers = []any{
		(*AuthMessage_ClientHello)(nil),
		(*AuthMessage_ServerProof)(nil),
		(*AuthMessage_ClientProof)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_auth_proto_rawDesc), len(file_internal_api_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_api_auth_proto_goTypes,
		DependencyIndexes: file_internal_api_auth_proto_depIdxs,
		MessageInfos:      file_internal_api_auth_proto_msgTypes,
	}.Build()
	File_internal_api_auth_proto = out.File
	file_internal_api_auth_proto_goTypes = nil
	file_internal_api_auth_proto_depIdxs = nil
}
