// ship workspace certificate format. Used by [internal/auth.CertAuth]
// to prove an agent's identity + capabilities are vouched for by
// the workspace master keypair. The master signs the
// [SignedCertContent] payload; the resulting `signature` is what
// peers verify against the master's public key.
//
// Wire shape: a [Cert] is one length-delimited frame on the
// /ship/auth/ stream when the CertAuth backend is in use. The
// payload bytes are stable: serialize SignedCertContent with
// protobuf's deterministic option before signing / verifying.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: internal/api/cert.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cert is the wire envelope: the signed claim + the master's
// signature over its serialized form.
type Cert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`     // serialized SignedCertContent
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"` // Ed25519 signature(master, content)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cert) Reset() {
	*x = Cert{}
	mi := &file_internal_api_cert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cert) ProtoMessage() {}

func (x *Cert) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_cert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cert.ProtoReflect.Descriptor instead.
func (*Cert) Descriptor() ([]byte, []int) {
	return file_internal_api_cert_proto_rawDescGZIP(), []int{0}
}

func (x *Cert) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Cert) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// SignedCertContent is the master-attested claim. Everything in
// here is bound to the signature; verifier deserializes after
// signature validation.
type SignedCertContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identifier the workspace assigns to this peer. ULIDs
	// recommended; not enforced at this layer.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Ed25519 public key of the agent. The agent proves ownership
	// by signing the auth handshake transcript with the matching
	// private key — see CertAuth for that flow.
	PeerPubkey []byte `protobuf:"bytes,2,opt,name=peer_pubkey,json=peerPubkey,proto3" json:"peer_pubkey,omitempty"`
	// Free-form label for logs / UI ("alice@host", "ci-runner"). Not
	// load-bearing for authorization.
	Label string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	// Capabilities granted to the cert holder. Mirrors
	// auth.Capabilities; serialized as a bitfield for compactness.
	// Bits: 1=Owner, 2=Write, 4=Resize. Owner implies Write+Resize
	// in the higher-level Capabilities consumer.
	CapsBits uint32 `protobuf:"varint,4,opt,name=caps_bits,json=capsBits,proto3" json:"caps_bits,omitempty"`
	// Issuance / expiry times. The verifier rejects a cert that
	// hasn't yet started (not_before in the future) or has expired
	// (not_after in the past).
	NotBefore *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	// Serial number distinguishes individual cert issuances even
	// when (agent_id, peer_pubkey) repeat. Revocation lists target
	// serials so a single compromise doesn't taint the agent's
	// identity forever.
	Serial string `protobuf:"bytes,7,opt,name=serial,proto3" json:"serial,omitempty"`
	// Workspace identifier. Verifier confirms it matches what it
	// expects; protects against accidentally accepting a cert from
	// another workspace that happens to share a master key (which
	// shouldn't happen but defense-in-depth).
	WorkspaceId   string `protobuf:"bytes,8,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedCertContent) Reset() {
	*x = SignedCertContent{}
	mi := &file_internal_api_cert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedCertContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedCertContent) ProtoMessage() {}

func (x *SignedCertContent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_cert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedCertContent.ProtoReflect.Descriptor instead.
func (*SignedCertContent) Descriptor() ([]byte, []int) {
	return file_internal_api_cert_proto_rawDescGZIP(), []int{1}
}

func (x *SignedCertContent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SignedCertContent) GetPeerPubkey() []byte {
	if x != nil {
		return x.PeerPubkey
	}
	return nil
}

func (x *SignedCertContent) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SignedCertContent) GetCapsBits() uint32 {
	if x != nil {
		return x.CapsBits
	}
	return 0
}

func (x *SignedCertContent) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *SignedCertContent) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *SignedCertContent) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *SignedCertContent) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

// CertHandshakeMessage is the wire envelope on /ship/auth/ when
// CertAuth is in use. The flow is symmetric: each side sends a
// CertHello with its cert, then a SignedNonce as proof of private-
// key control over the cert's declared peer_pubkey.
type CertHandshakeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CertHandshakeMessage_Hello
	//	*CertHandshakeMessage_Proof
	Payload       isCertHandshakeMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertHandshakeMessage) Reset() {
	*x = CertHandshakeMessage{}
	mi := &file_internal_api_cert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertHandshakeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertHandshakeMessage) ProtoMessage() {}

func (x *CertHandshakeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_cert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertHandshakeMessage.ProtoReflect.Descriptor instead.
func (*CertHandshakeMessage) Descriptor() ([]byte, []int) {
	return file_internal_api_cert_proto_rawDescGZIP(), []int{2}
}

func (x *CertHandshakeMessage) GetPayload() isCertHandshakeMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CertHandshakeMessage) GetHello() *CertHello {
	if x != nil {
		if x, ok := x.Payload.(*CertHandshakeMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *CertHandshakeMessage) GetProof() *SignedNonce {
	if x != nil {
		if x, ok := x.Payload.(*CertHandshakeMessage_Proof); ok {
			return x.Proof
		}
	}
	return nil
}

type isCertHandshakeMessage_Payload interface {
	isCertHandshakeMessage_Payload()
}

type CertHandshakeMessage_Hello struct {
	Hello *CertHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type CertHandshakeMessage_Proof struct {
	Proof *SignedNonce `protobuf:"bytes,2,opt,name=proof,proto3,oneof"`
}

func (*CertHandshakeMessage_Hello) isCertHandshakeMessage_Payload() {}

func (*CertHandshakeMessage_Proof) isCertHandshakeMessage_Payload() {}

// CertHello carries the sender's cert + a fresh nonce for the
// peer to sign as proof-of-control.
type CertHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cert          *Cert                  `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertHello) Reset() {
	*x = CertHello{}
	mi := &file_internal_api_cert_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertHello) ProtoMessage() {}

func (x *CertHello) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_cert_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertHello.ProtoReflect.Descriptor instead.
func (*CertHello) Descriptor() ([]byte, []int) {
	return file_internal_api_cert_proto_rawDescGZIP(), []int{3}
}

func (x *CertHello) GetCert() *Cert {
	if x != nil {
		return x.Cert
	}
	return nil
}

func (x *CertHello) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

// SignedNonce is the sender's Ed25519 signature over
// "ship-cert-v1" || peer_nonce. The peer verifies against the
// sender's cert.peer_pubkey.
type SignedNonce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedNonce) Reset() {
	*x = SignedNonce{}
	mi := &file_internal_api_cert_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedNonce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedNonce) ProtoMessage() {}

func (x *SignedNonce) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_cert_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedNonce.ProtoReflect.Descriptor instead.
func (*SignedNonce) Descriptor() ([]byte, []int) {
	return file_internal_api_cert_proto_rawDescGZIP(), []int{4}
}

func (x *SignedNonce) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_internal_api_cert_proto protoreflect.FileDescriptor

const file_internal_api_cert_proto_rawDesc = "" +
	"\n" +
	"\x17internal/api/cert.proto\x12\aship.v1\x1a\x1fgoogle/protobuf/timestamp.proto\">\n" +
	"\x04Cert\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xb1\x02\n" +
	"\x11SignedCertContent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vpeer_pubkey\x18\x02 \x01(\fR\n" +
	"peerPubkey\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x1b\n" +
	"\tcaps_bits\x18\x04 \x01(\rR\bcapsBits\x129\n" +
	"\n" +
	"not_before\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12\x16\n" +
	"\x06serial\x18\a \x01(\tR\x06serial\x12!\n" +
	"\fworkspace_id\x18\b \x01(\tR\vworkspaceId\"{\n" +
	"\x14CertHandshakeMessage\x12*\n" +
	"\x05hello\x18\x01 \x01(\v2\x12.ship.v1.CertHelloH\x00R\x05hello\x12,\n" +
	"\x05proof\x18\x02 \x01(\v2\x14.ship.v1.SignedNonceH\x00R\x05proofB\t\n" +
	"\apayload\"D\n" +
	"\tCertHello\x12!\n" +
	"\x04cert\x18\x01 \x01(\v2\r.ship.v1.CertR\x04cert\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\"+\n" +
	"\vSignedNonce\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignatureB7Z5github.com/firefly-engineering/mosey/internal/api;apib\x06proto3"

var (
	file_internal_api_cert_proto_rawDescOnce sync.Once
	file_internal_api_cert_proto_rawDescData []byte
)

func file_internal_api_cert_proto_rawDescGZIP() []byte {
	file_internal_api_cert_proto_rawDescOnce.Do(func() {
		file_internal_api_cert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_cert_proto_rawDesc), len(file_internal_api_cert_proto_rawDesc)))
	})
	return file_internal_api_cert_proto_rawDescData
}

var file_internal_api_cert_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_api_cert_proto_goTypes = []any{
	(*Cert)(nil),                  // 0: ship.v1.Cert
	(*SignedCertContent)(nil),     // 1: ship.v1.SignedCertContent
	(*CertHandshakeMessage)(nil),  // 2: ship.v1.CertHandshakeMessage
	(*CertHello)(nil),             // 3: ship.v1.CertHello
	(*SignedNonce)(nil),           // 4: ship.v1.SignedNonce
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_internal_api_cert_proto_depIdxs = []int32{
	5, // 0: ship.v1.SignedCertContent.not_before:type_name -> google.protobuf.Timestamp
	5, // 1: ship.v1.SignedCertContent.not_after:type_name -> google.protobuf.Timestamp
	3, // 2: ship.v1.CertHandshakeMessage.hello:type_name -> ship.v1.CertHello
	4, // 3: ship.v1.CertHandshakeMessage.proof:type_name -> ship.v1.SignedNonce
	0, // 4: ship.v1.CertHello.cert:type_name -> ship.v1.Cert
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_api_cert_proto_init() }
func file_internal_api_cert_proto_init() {
	if File_internal_api_cert_proto != nil {
		return
	}
	file_internal_api_cert_proto_msgTypes[2].OneofWrappers = []any{
		(*CertHandshakeMessage_Hello)(nil),
		(*CertHandshakeMessage_Proof)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_cert_proto_rawDesc), len(file_internal_api_cert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_api_cert_proto_goTypes,
		DependencyIndexes: file_internal_api_cert_proto_depIdxs,
		MessageInfos:      file_internal_api_cert_proto_msgTypes,
	}.Build()
	File_internal_api_cert_proto = out.File
	file_internal_api_cert_proto_goTypes = nil
	file_internal_api_cert_proto_depIdxs = nil
}
