// ship's control protocol — out-of-band messages between a vterm
// and an attached client. Carried on the libp2p stream
// `/ship/control/1.0.0` as length-delimited [ControlMessage]
// envelopes. Both sides may write; v1 only attach → vterm is used
// (Resize, Signal). v2 will add vterm → attach state events.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: internal/api/control.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Signal_Kind int32

const (
	Signal_KIND_UNSPECIFIED Signal_Kind = 0
	Signal_KIND_HUP         Signal_Kind = 1
	Signal_KIND_INT         Signal_Kind = 2
	Signal_KIND_TERM        Signal_Kind = 3
	Signal_KIND_USR1        Signal_Kind = 4
	Signal_KIND_USR2        Signal_Kind = 5
)

// Enum value maps for Signal_Kind.
var (
	Signal_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_HUP",
		2: "KIND_INT",
		3: "KIND_TERM",
		4: "KIND_USR1",
		5: "KIND_USR2",
	}
	Signal_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_HUP":         1,
		"KIND_INT":         2,
		"KIND_TERM":        3,
		"KIND_USR1":        4,
		"KIND_USR2":        5,
	}
)

func (x Signal_Kind) Enum() *Signal_Kind {
	p := new(Signal_Kind)
	*p = x
	return p
}

func (x Signal_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Signal_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_api_control_proto_enumTypes[0].Descriptor()
}

func (Signal_Kind) Type() protoreflect.EnumType {
	return &file_internal_api_control_proto_enumTypes[0]
}

func (x Signal_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Signal_Kind.Descriptor instead.
func (Signal_Kind) EnumDescriptor() ([]byte, []int) {
	return file_internal_api_control_proto_rawDescGZIP(), []int{2, 0}
}

// ControlMessage is the envelope carried on /ship/control/. Each
// frame is length-delimited (varint length prefix + serialized
// proto) so a single stream multiplexes typed messages without a
// separate framing layer.
//
// Adding a new payload variant is a non-breaking change as long as
// the new field uses a fresh tag number. Old peers ignore unknown
// payloads; new peers should fall back gracefully when they receive
// an envelope whose payload they don't understand (e.g. log and
// continue).
type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlMessage_Resize
	//	*ControlMessage_Signal
	Payload       isControlMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_internal_api_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_internal_api_control_proto_rawDescGZIP(), []int{0}
}

func (x *ControlMessage) GetPayload() isControlMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlMessage) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *ControlMessage) GetSignal() *Signal {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

type isControlMessage_Payload interface {
	isControlMessage_Payload()
}

type ControlMessage_Resize struct {
	Resize *Resize `protobuf:"bytes,1,opt,name=resize,proto3,oneof"`
}

type ControlMessage_Signal struct {
	Signal *Signal `protobuf:"bytes,2,opt,name=signal,proto3,oneof"`
}

func (*ControlMessage_Resize) isControlMessage_Payload() {}

func (*ControlMessage_Signal) isControlMessage_Payload() {}

// Resize requests that the remote PTY be set to the given size
// (TIOCSWINSZ-equivalent). Attach sends one on connect and again
// whenever its local terminal SIGWINCH fires.
type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_internal_api_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_internal_api_control_proto_rawDescGZIP(), []int{1}
}

func (x *Resize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

// Signal forwards a process signal to the vterm's child process.
// Maps to a small, deliberately constrained set so v1 isn't a
// signal-injection vector; the wider POSIX set can be reconsidered
// once the authn story matures.
type Signal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          Signal_Kind            `protobuf:"varint,1,opt,name=kind,proto3,enum=ship.v1.Signal_Kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_internal_api_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_internal_api_control_proto_rawDescGZIP(), []int{2}
}

func (x *Signal) GetKind() Signal_Kind {
	if x != nil {
		return x.Kind
	}
	return Signal_KIND_UNSPECIFIED
}

var File_internal_api_control_proto protoreflect.FileDescriptor

const file_internal_api_control_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/api/control.proto\x12\aship.v1\"q\n" +
	"\x0eControlMessage\x12)\n" +
	"\x06resize\x18\x01 \x01(\v2\x0f.ship.v1.ResizeH\x00R\x06resize\x12)\n" +
	"\x06signal\x18\x02 \x01(\v2\x0f.ship.v1.SignalH\x00R\x06signalB\t\n" +
	"\apayload\"0\n" +
	"\x06Resize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"\x99\x01\n" +
	"\x06Signal\x12(\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x14.ship.v1.Signal.KindR\x04kind\"e\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bKIND_HUP\x10\x01\x12\f\n" +
	"\bKIND_INT\x10\x02\x12\r\n" +
	"\tKIND_TERM\x10\x03\x12\r\n" +
	"\tKIND_USR1\x10\x04\x12\r\n" +
	"\tKIND_USR2\x10\x05B6Z4github.com/firefly-engineering/ship/internal/api;apib\x06proto3"

var (
	file_internal_api_control_proto_rawDescOnce sync.Once
	file_internal_api_control_proto_rawDescData []byte
)

func file_internal_api_control_proto_rawDescGZIP() []byte {
	file_internal_api_control_proto_rawDescOnce.Do(func() {
		file_internal_api_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_control_proto_rawDesc), len(file_internal_api_control_proto_rawDesc)))
	})
	return file_internal_api_control_proto_rawDescData
}

var file_internal_api_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_api_control_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_api_control_proto_goTypes = []any{
	(Signal_Kind)(0),       // 0: ship.v1.Signal.Kind
	(*ControlMessage)(nil), // 1: ship.v1.ControlMessage
	(*Resize)(nil),         // 2: ship.v1.Resize
	(*Signal)(nil),         // 3: ship.v1.Signal
}
var file_internal_api_control_proto_depIdxs = []int32{
	2, // 0: ship.v1.ControlMessage.resize:type_name -> ship.v1.Resize
	3, // 1: ship.v1.ControlMessage.signal:type_name -> ship.v1.Signal
	0, // 2: ship.v1.Signal.kind:type_name -> ship.v1.Signal.Kind
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_api_control_proto_init() }
func file_internal_api_control_proto_init() {
	if File_internal_api_control_proto != nil {
		return
	}
	file_internal_api_control_proto_msgTypes[0].OneofWrappers = []any{
		(*ControlMessage_Resize)(nil),
		(*ControlMessage_Signal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_control_proto_rawDesc), len(file_internal_api_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_api_control_proto_goTypes,
		DependencyIndexes: file_internal_api_control_proto_depIdxs,
		EnumInfos:         file_internal_api_control_proto_enumTypes,
		MessageInfos:      file_internal_api_control_proto_msgTypes,
	}.Build()
	File_internal_api_control_proto = out.File
	file_internal_api_control_proto_goTypes = nil
	file_internal_api_control_proto_depIdxs = nil
}
