// mosey's control protocol — out-of-band messages between a vterm
// and an attached client. Carried on the libp2p stream
// `/mosey/control/1.0.0` as length-delimited [ControlMessage]
// envelopes. Both sides may write; v1 only attach → vterm is used
// (Resize, Signal). v2 will add vterm → attach state events.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: api/control.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Signal_Kind int32

const (
	Signal_KIND_UNSPECIFIED Signal_Kind = 0
	Signal_KIND_HUP         Signal_Kind = 1
	Signal_KIND_INT         Signal_Kind = 2
	Signal_KIND_TERM        Signal_Kind = 3
	Signal_KIND_USR1        Signal_Kind = 4
	Signal_KIND_USR2        Signal_Kind = 5
)

// Enum value maps for Signal_Kind.
var (
	Signal_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_HUP",
		2: "KIND_INT",
		3: "KIND_TERM",
		4: "KIND_USR1",
		5: "KIND_USR2",
	}
	Signal_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_HUP":         1,
		"KIND_INT":         2,
		"KIND_TERM":        3,
		"KIND_USR1":        4,
		"KIND_USR2":        5,
	}
)

func (x Signal_Kind) Enum() *Signal_Kind {
	p := new(Signal_Kind)
	*p = x
	return p
}

func (x Signal_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Signal_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_control_proto_enumTypes[0].Descriptor()
}

func (Signal_Kind) Type() protoreflect.EnumType {
	return &file_api_control_proto_enumTypes[0]
}

func (x Signal_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Signal_Kind.Descriptor instead.
func (Signal_Kind) EnumDescriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{2, 0}
}

type SetMode_Kind int32

const (
	SetMode_KIND_UNSPECIFIED      SetMode_Kind = 0
	SetMode_KIND_SUPERSEDE        SetMode_Kind = 1
	SetMode_KIND_EXCLUSIVE        SetMode_Kind = 2
	SetMode_KIND_PRIMARY_OBSERVER SetMode_Kind = 3
	SetMode_KIND_MULTI_WRITE      SetMode_Kind = 4
)

// Enum value maps for SetMode_Kind.
var (
	SetMode_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_SUPERSEDE",
		2: "KIND_EXCLUSIVE",
		3: "KIND_PRIMARY_OBSERVER",
		4: "KIND_MULTI_WRITE",
	}
	SetMode_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":      0,
		"KIND_SUPERSEDE":        1,
		"KIND_EXCLUSIVE":        2,
		"KIND_PRIMARY_OBSERVER": 3,
		"KIND_MULTI_WRITE":      4,
	}
)

func (x SetMode_Kind) Enum() *SetMode_Kind {
	p := new(SetMode_Kind)
	*p = x
	return p
}

func (x SetMode_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetMode_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_control_proto_enumTypes[1].Descriptor()
}

func (SetMode_Kind) Type() protoreflect.EnumType {
	return &file_api_control_proto_enumTypes[1]
}

func (x SetMode_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetMode_Kind.Descriptor instead.
func (SetMode_Kind) EnumDescriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{3, 0}
}

// ControlMessage is the envelope carried on /mosey/control/. Each
// frame is length-delimited (varint length prefix + serialized
// proto) so a single stream multiplexes typed messages without a
// separate framing layer.
//
// Adding a new payload variant is a non-breaking change as long as
// the new field uses a fresh tag number. Old peers ignore unknown
// payloads; new peers should fall back gracefully when they receive
// an envelope whose payload they don't understand (e.g. log and
// continue).
type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlMessage_Resize
	//	*ControlMessage_Signal
	//	*ControlMessage_SetMode
	//	*ControlMessage_Demote
	//	*ControlMessage_ListClients
	//	*ControlMessage_ClientList
	//	*ControlMessage_Promote
	//	*ControlMessage_Kick
	Payload       isControlMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_api_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{0}
}

func (x *ControlMessage) GetPayload() isControlMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlMessage) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *ControlMessage) GetSignal() *Signal {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

func (x *ControlMessage) GetSetMode() *SetMode {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_SetMode); ok {
			return x.SetMode
		}
	}
	return nil
}

func (x *ControlMessage) GetDemote() *Demote {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Demote); ok {
			return x.Demote
		}
	}
	return nil
}

func (x *ControlMessage) GetListClients() *ListClients {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_ListClients); ok {
			return x.ListClients
		}
	}
	return nil
}

func (x *ControlMessage) GetClientList() *ClientList {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_ClientList); ok {
			return x.ClientList
		}
	}
	return nil
}

func (x *ControlMessage) GetPromote() *Promote {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Promote); ok {
			return x.Promote
		}
	}
	return nil
}

func (x *ControlMessage) GetKick() *Kick {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Kick); ok {
			return x.Kick
		}
	}
	return nil
}

type isControlMessage_Payload interface {
	isControlMessage_Payload()
}

type ControlMessage_Resize struct {
	Resize *Resize `protobuf:"bytes,1,opt,name=resize,proto3,oneof"`
}

type ControlMessage_Signal struct {
	Signal *Signal `protobuf:"bytes,2,opt,name=signal,proto3,oneof"`
}

type ControlMessage_SetMode struct {
	SetMode *SetMode `protobuf:"bytes,3,opt,name=set_mode,json=setMode,proto3,oneof"`
}

type ControlMessage_Demote struct {
	Demote *Demote `protobuf:"bytes,4,opt,name=demote,proto3,oneof"`
}

type ControlMessage_ListClients struct {
	ListClients *ListClients `protobuf:"bytes,5,opt,name=list_clients,json=listClients,proto3,oneof"`
}

type ControlMessage_ClientList struct {
	ClientList *ClientList `protobuf:"bytes,6,opt,name=client_list,json=clientList,proto3,oneof"`
}

type ControlMessage_Promote struct {
	Promote *Promote `protobuf:"bytes,7,opt,name=promote,proto3,oneof"`
}

type ControlMessage_Kick struct {
	Kick *Kick `protobuf:"bytes,8,opt,name=kick,proto3,oneof"`
}

func (*ControlMessage_Resize) isControlMessage_Payload() {}

func (*ControlMessage_Signal) isControlMessage_Payload() {}

func (*ControlMessage_SetMode) isControlMessage_Payload() {}

func (*ControlMessage_Demote) isControlMessage_Payload() {}

func (*ControlMessage_ListClients) isControlMessage_Payload() {}

func (*ControlMessage_ClientList) isControlMessage_Payload() {}

func (*ControlMessage_Promote) isControlMessage_Payload() {}

func (*ControlMessage_Kick) isControlMessage_Payload() {}

// Resize requests that the remote PTY be set to the given size
// (TIOCSWINSZ-equivalent). Attach sends one on connect and again
// whenever its local terminal SIGWINCH fires.
type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_api_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{1}
}

func (x *Resize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

// Signal forwards a process signal to the vterm's child process.
// Maps to a small, deliberately constrained set so v1 isn't a
// signal-injection vector; the wider POSIX set can be reconsidered
// once the authn story matures.
type Signal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          Signal_Kind            `protobuf:"varint,1,opt,name=kind,proto3,enum=mosey.v1.Signal_Kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_api_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{2}
}

func (x *Signal) GetKind() Signal_Kind {
	if x != nil {
		return x.Kind
	}
	return Signal_KIND_UNSPECIFIED
}

// SetMode switches the vterm session's multi-client mode at
// runtime. Owner-only — vterm silently drops the message from any
// client whose [Identity] doesn't hold the Owner capability. The
// new mode applies to *future* attaches; existing clients keep
// their current permissions (use Demote to step down, future
// Kick/Promote RPCs to manage others).
type SetMode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          SetMode_Kind           `protobuf:"varint,1,opt,name=kind,proto3,enum=mosey.v1.SetMode_Kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMode) Reset() {
	*x = SetMode{}
	mi := &file_api_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMode) ProtoMessage() {}

func (x *SetMode) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMode.ProtoReflect.Descriptor instead.
func (*SetMode) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{3}
}

func (x *SetMode) GetKind() SetMode_Kind {
	if x != nil {
		return x.Kind
	}
	return SetMode_KIND_UNSPECIFIED
}

// Demote is the self-service write-permission drop. The client
// sending Demote loses its write + resize permissions; if it
// happened to hold the PrimaryObserver writer seat, the seat
// becomes vacant (no auto-promotion). Useful for "going AFK; don't
// let me typo into prod." No cap required — any client can demote
// itself.
type Demote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Demote) Reset() {
	*x = Demote{}
	mi := &file_api_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Demote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Demote) ProtoMessage() {}

func (x *Demote) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Demote.ProtoReflect.Descriptor instead.
func (*Demote) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{4}
}

// ListClients asks the vterm to enumerate currently-attached
// clients. The server replies on the same control stream with a
// ClientList message. Any authenticated client may issue this —
// useful to non-Owner clients too (e.g. "who else is here").
type ListClients struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClients) Reset() {
	*x = ListClients{}
	mi := &file_api_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClients) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClients) ProtoMessage() {}

func (x *ListClients) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClients.ProtoReflect.Descriptor instead.
func (*ListClients) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{5}
}

// ClientList is the vterm's response to ListClients. Carries one
// ClientInfo per attached client at the moment the request was
// handled. The list is a snapshot, not a subscription.
type ClientList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*ClientInfo          `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientList) Reset() {
	*x = ClientList{}
	mi := &file_api_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientList) ProtoMessage() {}

func (x *ClientList) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientList.ProtoReflect.Descriptor instead.
func (*ClientList) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{6}
}

func (x *ClientList) GetClients() []*ClientInfo {
	if x != nil {
		return x.Clients
	}
	return nil
}

// ClientInfo describes one attached client in the registry. Stable
// fields only — internal session bookkeeping (channel depths, etc.)
// stays off the wire.
type ClientInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identifier within the vterm session's lifetime. Used to
	// target Promote / Kick. Not reused after a client disconnects.
	ClientId int64 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Auth-layer role label ("owner", "reader", or a cert subject).
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// True when this client currently holds write permission given
	// the session's mode + dynamic demotions.
	CanWrite bool `protobuf:"varint,3,opt,name=can_write,json=canWrite,proto3" json:"can_write,omitempty"`
	// Latest reported terminal geometry, or zero if the client
	// hasn't sent a Resize yet.
	Cols          uint32 `protobuf:"varint,4,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32 `protobuf:"varint,5,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_api_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{7}
}

func (x *ClientInfo) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *ClientInfo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ClientInfo) GetCanWrite() bool {
	if x != nil {
		return x.CanWrite
	}
	return false
}

func (x *ClientInfo) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ClientInfo) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

// Promote flips a client's write permission to true. Owner-only.
// In PrimaryObserver, the promoted client becomes the writer seat
// holder (a prior writer is demoted to observer). In MultiWrite /
// Supersede / Exclusive, this is mostly a no-op since writers are
// already permitted; the message exists for symmetry with Demote.
type Promote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int64                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Promote) Reset() {
	*x = Promote{}
	mi := &file_api_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Promote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Promote) ProtoMessage() {}

func (x *Promote) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Promote.ProtoReflect.Descriptor instead.
func (*Promote) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{8}
}

func (x *Promote) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

// Kick forcibly disconnects a client. Owner-only. The target's
// PTY stream is closed; its attach.Run exits cleanly.
type Kick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int64                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kick) Reset() {
	*x = Kick{}
	mi := &file_api_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kick) ProtoMessage() {}

func (x *Kick) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kick.ProtoReflect.Descriptor instead.
func (*Kick) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{9}
}

func (x *Kick) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

var File_api_control_proto protoreflect.FileDescriptor

const file_api_control_proto_rawDesc = "" +
	"\n" +
	"\x11api/control.proto\x12\bmosey.v1\"\x99\x03\n" +
	"\x0eControlMessage\x12*\n" +
	"\x06resize\x18\x01 \x01(\v2\x10.mosey.v1.ResizeH\x00R\x06resize\x12*\n" +
	"\x06signal\x18\x02 \x01(\v2\x10.mosey.v1.SignalH\x00R\x06signal\x12.\n" +
	"\bset_mode\x18\x03 \x01(\v2\x11.mosey.v1.SetModeH\x00R\asetMode\x12*\n" +
	"\x06demote\x18\x04 \x01(\v2\x10.mosey.v1.DemoteH\x00R\x06demote\x12:\n" +
	"\flist_clients\x18\x05 \x01(\v2\x15.mosey.v1.ListClientsH\x00R\vlistClients\x127\n" +
	"\vclient_list\x18\x06 \x01(\v2\x14.mosey.v1.ClientListH\x00R\n" +
	"clientList\x12-\n" +
	"\apromote\x18\a \x01(\v2\x11.mosey.v1.PromoteH\x00R\apromote\x12$\n" +
	"\x04kick\x18\b \x01(\v2\x0e.mosey.v1.KickH\x00R\x04kickB\t\n" +
	"\apayload\"0\n" +
	"\x06Resize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"\x9a\x01\n" +
	"\x06Signal\x12)\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x15.mosey.v1.Signal.KindR\x04kind\"e\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bKIND_HUP\x10\x01\x12\f\n" +
	"\bKIND_INT\x10\x02\x12\r\n" +
	"\tKIND_TERM\x10\x03\x12\r\n" +
	"\tKIND_USR1\x10\x04\x12\r\n" +
	"\tKIND_USR2\x10\x05\"\xac\x01\n" +
	"\aSetMode\x12*\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x16.mosey.v1.SetMode.KindR\x04kind\"u\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eKIND_SUPERSEDE\x10\x01\x12\x12\n" +
	"\x0eKIND_EXCLUSIVE\x10\x02\x12\x19\n" +
	"\x15KIND_PRIMARY_OBSERVER\x10\x03\x12\x14\n" +
	"\x10KIND_MULTI_WRITE\x10\x04\"\b\n" +
	"\x06Demote\"\r\n" +
	"\vListClients\"<\n" +
	"\n" +
	"ClientList\x12.\n" +
	"\aclients\x18\x01 \x03(\v2\x14.mosey.v1.ClientInfoR\aclients\"\x84\x01\n" +
	"\n" +
	"ClientInfo\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x03R\bclientId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1b\n" +
	"\tcan_write\x18\x03 \x01(\bR\bcanWrite\x12\x12\n" +
	"\x04cols\x18\x04 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x05 \x01(\rR\x04rows\"&\n" +
	"\aPromote\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x03R\bclientId\"#\n" +
	"\x04Kick\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x03R\bclientIdB.Z,github.com/firefly-engineering/mosey/api;apib\x06proto3"

var (
	file_api_control_proto_rawDescOnce sync.Once
	file_api_control_proto_rawDescData []byte
)

func file_api_control_proto_rawDescGZIP() []byte {
	file_api_control_proto_rawDescOnce.Do(func() {
		file_api_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_control_proto_rawDesc), len(file_api_control_proto_rawDesc)))
	})
	return file_api_control_proto_rawDescData
}

var file_api_control_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_control_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_control_proto_goTypes = []any{
	(Signal_Kind)(0),       // 0: mosey.v1.Signal.Kind
	(SetMode_Kind)(0),      // 1: mosey.v1.SetMode.Kind
	(*ControlMessage)(nil), // 2: mosey.v1.ControlMessage
	(*Resize)(nil),         // 3: mosey.v1.Resize
	(*Signal)(nil),         // 4: mosey.v1.Signal
	(*SetMode)(nil),        // 5: mosey.v1.SetMode
	(*Demote)(nil),         // 6: mosey.v1.Demote
	(*ListClients)(nil),    // 7: mosey.v1.ListClients
	(*ClientList)(nil),     // 8: mosey.v1.ClientList
	(*ClientInfo)(nil),     // 9: mosey.v1.ClientInfo
	(*Promote)(nil),        // 10: mosey.v1.Promote
	(*Kick)(nil),           // 11: mosey.v1.Kick
}
var file_api_control_proto_depIdxs = []int32{
	3,  // 0: mosey.v1.ControlMessage.resize:type_name -> mosey.v1.Resize
	4,  // 1: mosey.v1.ControlMessage.signal:type_name -> mosey.v1.Signal
	5,  // 2: mosey.v1.ControlMessage.set_mode:type_name -> mosey.v1.SetMode
	6,  // 3: mosey.v1.ControlMessage.demote:type_name -> mosey.v1.Demote
	7,  // 4: mosey.v1.ControlMessage.list_clients:type_name -> mosey.v1.ListClients
	8,  // 5: mosey.v1.ControlMessage.client_list:type_name -> mosey.v1.ClientList
	10, // 6: mosey.v1.ControlMessage.promote:type_name -> mosey.v1.Promote
	11, // 7: mosey.v1.ControlMessage.kick:type_name -> mosey.v1.Kick
	0,  // 8: mosey.v1.Signal.kind:type_name -> mosey.v1.Signal.Kind
	1,  // 9: mosey.v1.SetMode.kind:type_name -> mosey.v1.SetMode.Kind
	9,  // 10: mosey.v1.ClientList.clients:type_name -> mosey.v1.ClientInfo
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_control_proto_init() }
func file_api_control_proto_init() {
	if File_api_control_proto != nil {
		return
	}
	file_api_control_proto_msgTypes[0].OneofWrappers = []any{
		(*ControlMessage_Resize)(nil),
		(*ControlMessage_Signal)(nil),
		(*ControlMessage_SetMode)(nil),
		(*ControlMessage_Demote)(nil),
		(*ControlMessage_ListClients)(nil),
		(*ControlMessage_ClientList)(nil),
		(*ControlMessage_Promote)(nil),
		(*ControlMessage_Kick)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_control_proto_rawDesc), len(file_api_control_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_control_proto_goTypes,
		DependencyIndexes: file_api_control_proto_depIdxs,
		EnumInfos:         file_api_control_proto_enumTypes,
		MessageInfos:      file_api_control_proto_msgTypes,
	}.Build()
	File_api_control_proto = out.File
	file_api_control_proto_goTypes = nil
	file_api_control_proto_depIdxs = nil
}
