// mosey wallet-auth handshake + delegation wire formats. Carried on
// /mosey/auth/1.0.0 as length-delimited [WalletHandshakeMessage]
// envelopes when the wallet authenticator is in use.
//
// Mutual but asymmetric: the server proves control of the on-chain
// session identity (session_key); the client proves control of an
// ephemeral connection key (K_c) and presents a delegation chain that
// roots that key's capabilities in on-chain ownership or a grant.
//
//   1. Client → Server: WalletHello { client_pubkey, nonce_c, delegation_chain }
//   2. Server → Client: WalletChallenge { session_key, nonce_s, server_sig }
//   3. Client → Server: WalletProof { client_sig }
//
//   server_sig = Ed25519(session_key, "mosey-wallet-v1:server" || nonce_c || nonce_s || session_id)
//   client_sig = Ed25519(K_c,         "mosey-wallet-v1:client" || nonce_s || nonce_c || session_id)
//
// session_id is the session_key's bytes; the client checks the server's
// session_key equals the session it dialed (mutual auth, so a MITM
// cannot impersonate the session). Direction-specific labels stop a
// signature being replayed the other way.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: api/wallet.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WalletHandshakeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*WalletHandshakeMessage_Hello
	//	*WalletHandshakeMessage_Challenge
	//	*WalletHandshakeMessage_Proof
	Kind          isWalletHandshakeMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletHandshakeMessage) Reset() {
	*x = WalletHandshakeMessage{}
	mi := &file_api_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletHandshakeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletHandshakeMessage) ProtoMessage() {}

func (x *WalletHandshakeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletHandshakeMessage.ProtoReflect.Descriptor instead.
func (*WalletHandshakeMessage) Descriptor() ([]byte, []int) {
	return file_api_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *WalletHandshakeMessage) GetKind() isWalletHandshakeMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *WalletHandshakeMessage) GetHello() *WalletHello {
	if x != nil {
		if x, ok := x.Kind.(*WalletHandshakeMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WalletHandshakeMessage) GetChallenge() *WalletChallenge {
	if x != nil {
		if x, ok := x.Kind.(*WalletHandshakeMessage_Challenge); ok {
			return x.Challenge
		}
	}
	return nil
}

func (x *WalletHandshakeMessage) GetProof() *WalletProof {
	if x != nil {
		if x, ok := x.Kind.(*WalletHandshakeMessage_Proof); ok {
			return x.Proof
		}
	}
	return nil
}

type isWalletHandshakeMessage_Kind interface {
	isWalletHandshakeMessage_Kind()
}

type WalletHandshakeMessage_Hello struct {
	Hello *WalletHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type WalletHandshakeMessage_Challenge struct {
	Challenge *WalletChallenge `protobuf:"bytes,2,opt,name=challenge,proto3,oneof"`
}

type WalletHandshakeMessage_Proof struct {
	Proof *WalletProof `protobuf:"bytes,3,opt,name=proof,proto3,oneof"`
}

func (*WalletHandshakeMessage_Hello) isWalletHandshakeMessage_Kind() {}

func (*WalletHandshakeMessage_Challenge) isWalletHandshakeMessage_Kind() {}

func (*WalletHandshakeMessage_Proof) isWalletHandshakeMessage_Kind() {}

// WalletHello is the dialer's opener: the ephemeral connection key it
// will prove control of, a 32-byte nonce, and the delegation chain
// (root → leaf) that authorizes that key. The chain's leaf delegate
// must equal client_pubkey.
type WalletHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientPubkey    []byte                 `protobuf:"bytes,1,opt,name=client_pubkey,json=clientPubkey,proto3" json:"client_pubkey,omitempty"`
	NonceC          []byte                 `protobuf:"bytes,2,opt,name=nonce_c,json=nonceC,proto3" json:"nonce_c,omitempty"`
	DelegationChain []*Delegation          `protobuf:"bytes,3,rep,name=delegation_chain,json=delegationChain,proto3" json:"delegation_chain,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WalletHello) Reset() {
	*x = WalletHello{}
	mi := &file_api_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletHello) ProtoMessage() {}

func (x *WalletHello) ProtoReflect() protoreflect.Message {
	mi := &file_api_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletHello.ProtoReflect.Descriptor instead.
func (*WalletHello) Descriptor() ([]byte, []int) {
	return file_api_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *WalletHello) GetClientPubkey() []byte {
	if x != nil {
		return x.ClientPubkey
	}
	return nil
}

func (x *WalletHello) GetNonceC() []byte {
	if x != nil {
		return x.NonceC
	}
	return nil
}

func (x *WalletHello) GetDelegationChain() []*Delegation {
	if x != nil {
		return x.DelegationChain
	}
	return nil
}

// WalletChallenge is the listener's response: the on-chain session
// identity, its own 32-byte nonce, and a signature by session_key over
// the transcript proving it controls the session.
type WalletChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    []byte                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	NonceS        []byte                 `protobuf:"bytes,2,opt,name=nonce_s,json=nonceS,proto3" json:"nonce_s,omitempty"`
	ServerSig     []byte                 `protobuf:"bytes,3,opt,name=server_sig,json=serverSig,proto3" json:"server_sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletChallenge) Reset() {
	*x = WalletChallenge{}
	mi := &file_api_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletChallenge) ProtoMessage() {}

func (x *WalletChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_api_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletChallenge.ProtoReflect.Descriptor instead.
func (*WalletChallenge) Descriptor() ([]byte, []int) {
	return file_api_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *WalletChallenge) GetSessionKey() []byte {
	if x != nil {
		return x.SessionKey
	}
	return nil
}

func (x *WalletChallenge) GetNonceS() []byte {
	if x != nil {
		return x.NonceS
	}
	return nil
}

func (x *WalletChallenge) GetServerSig() []byte {
	if x != nil {
		return x.ServerSig
	}
	return nil
}

// WalletProof is the dialer's closing proof: client_pubkey's signature
// over the transcript, proving live control of the connection key.
type WalletProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientSig     []byte                 `protobuf:"bytes,1,opt,name=client_sig,json=clientSig,proto3" json:"client_sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletProof) Reset() {
	*x = WalletProof{}
	mi := &file_api_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletProof) ProtoMessage() {}

func (x *WalletProof) ProtoReflect() protoreflect.Message {
	mi := &file_api_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletProof.ProtoReflect.Descriptor instead.
func (*WalletProof) Descriptor() ([]byte, []int) {
	return file_api_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *WalletProof) GetClientSig() []byte {
	if x != nil {
		return x.ClientSig
	}
	return nil
}

// Delegation is the off-chain capability envelope: the canonical content
// text (see wallet.Fields) plus the delegator's Ed25519 signature over
// it. The delegator is named inside content.
type Delegation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delegation) Reset() {
	*x = Delegation{}
	mi := &file_api_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delegation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delegation) ProtoMessage() {}

func (x *Delegation) ProtoReflect() protoreflect.Message {
	mi := &file_api_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delegation.ProtoReflect.Descriptor instead.
func (*Delegation) Descriptor() ([]byte, []int) {
	return file_api_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *Delegation) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Delegation) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_api_wallet_proto protoreflect.FileDescriptor

const file_api_wallet_proto_rawDesc = "" +
	"\n" +
	"\x10api/wallet.proto\x12\bmosey.v1\"\xb9\x01\n" +
	"\x16WalletHandshakeMessage\x12-\n" +
	"\x05hello\x18\x01 \x01(\v2\x15.mosey.v1.WalletHelloH\x00R\x05hello\x129\n" +
	"\tchallenge\x18\x02 \x01(\v2\x19.mosey.v1.WalletChallengeH\x00R\tchallenge\x12-\n" +
	"\x05proof\x18\x03 \x01(\v2\x15.mosey.v1.WalletProofH\x00R\x05proofB\x06\n" +
	"\x04kind\"\x8c\x01\n" +
	"\vWalletHello\x12#\n" +
	"\rclient_pubkey\x18\x01 \x01(\fR\fclientPubkey\x12\x17\n" +
	"\anonce_c\x18\x02 \x01(\fR\x06nonceC\x12?\n" +
	"\x10delegation_chain\x18\x03 \x03(\v2\x14.mosey.v1.DelegationR\x0fdelegationChain\"j\n" +
	"\x0fWalletChallenge\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\fR\n" +
	"sessionKey\x12\x17\n" +
	"\anonce_s\x18\x02 \x01(\fR\x06nonceS\x12\x1d\n" +
	"\n" +
	"server_sig\x18\x03 \x01(\fR\tserverSig\",\n" +
	"\vWalletProof\x12\x1d\n" +
	"\n" +
	"client_sig\x18\x01 \x01(\fR\tclientSig\"D\n" +
	"\n" +
	"Delegation\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignatureB.Z,github.com/firefly-engineering/mosey/api;apib\x06proto3"

var (
	file_api_wallet_proto_rawDescOnce sync.Once
	file_api_wallet_proto_rawDescData []byte
)

func file_api_wallet_proto_rawDescGZIP() []byte {
	file_api_wallet_proto_rawDescOnce.Do(func() {
		file_api_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_wallet_proto_rawDesc), len(file_api_wallet_proto_rawDesc)))
	})
	return file_api_wallet_proto_rawDescData
}

var file_api_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_wallet_proto_goTypes = []any{
	(*WalletHandshakeMessage)(nil), // 0: mosey.v1.WalletHandshakeMessage
	(*WalletHello)(nil),            // 1: mosey.v1.WalletHello
	(*WalletChallenge)(nil),        // 2: mosey.v1.WalletChallenge
	(*WalletProof)(nil),            // 3: mosey.v1.WalletProof
	(*Delegation)(nil),             // 4: mosey.v1.Delegation
}
var file_api_wallet_proto_depIdxs = []int32{
	1, // 0: mosey.v1.WalletHandshakeMessage.hello:type_name -> mosey.v1.WalletHello
	2, // 1: mosey.v1.WalletHandshakeMessage.challenge:type_name -> mosey.v1.WalletChallenge
	3, // 2: mosey.v1.WalletHandshakeMessage.proof:type_name -> mosey.v1.WalletProof
	4, // 3: mosey.v1.WalletHello.delegation_chain:type_name -> mosey.v1.Delegation
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_wallet_proto_init() }
func file_api_wallet_proto_init() {
	if File_api_wallet_proto != nil {
		return
	}
	file_api_wallet_proto_msgTypes[0].OneofWrappers = []any{
		(*WalletHandshakeMessage_Hello)(nil),
		(*WalletHandshakeMessage_Challenge)(nil),
		(*WalletHandshakeMessage_Proof)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_wallet_proto_rawDesc), len(file_api_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_wallet_proto_goTypes,
		DependencyIndexes: file_api_wallet_proto_depIdxs,
		MessageInfos:      file_api_wallet_proto_msgTypes,
	}.Build()
	File_api_wallet_proto = out.File
	file_api_wallet_proto_goTypes = nil
	file_api_wallet_proto_depIdxs = nil
}
